In [35]:
import numpy  as np 

theta1=(45/180)*np.pi
theta2=(-45/180)*np.pi
alpha1=(90/180)*np.pi
d1=0.044
d2=0
l1=0.148
l2=0.219

In [36]:
PT=[[theta1,alpha1,d1,l1],#Denavit Hartenberg Table for singe leg
   [theta2,0,0,l2]]

In [37]:
i=0
T0_1=[[np.cos(PT[i][0]),-np.sin(PT[i][0])*np.cos(PT[i][1]),np.sin(PT[i][0])*np.sin(PT[i][1]),l1*np.cos(PT[i][0])],
        [np.sin(PT[i][0]),np.cos(PT[i][0])*np.cos(PT[i][1]),-np.cos(PT[i][0])*np.sin(PT[i][1]),l1*np.sin(PT[i][0])],
        [0,np.sin(PT[i][1]),np.cos(PT[i][1]),d1],
        [0,0,0,1]]

In [38]:
print(np.matrix(T0_1))

[[ 7.07106781e-01 -4.32978028e-17  7.07106781e-01  1.04651804e-01]
 [ 7.07106781e-01  4.32978028e-17 -7.07106781e-01  1.04651804e-01]
 [ 0.00000000e+00  1.00000000e+00  6.12323400e-17  4.40000000e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [39]:
i=1
T1_2=[[np.cos(PT[i][0]),-np.sin(PT[i][0])*np.cos(PT[i][1]),np.sin(PT[i][0])*np.sin(PT[i][1]),l2*np.cos(PT[i][0])],
        [np.sin(PT[i][0]),np.cos(PT[i][0])*np.cos(PT[i][1]),-np.cos(PT[i][0])*np.sin(PT[i][1]),l2*np.sin(PT[i][0])],
        [0,np.sin(PT[i][1]),np.cos(PT[i][1]),d2],
        [0,0,0,1]]

In [40]:
print(np.matrix(T1_2))

[[ 0.70710678  0.70710678 -0.          0.15485639]
 [-0.70710678  0.70710678 -0.         -0.15485639]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]


In [41]:
T0_2=np.dot(T0_1,T1_2)

In [42]:
print(np.matrix(T0_2))

[[ 5.00000000e-01  5.00000000e-01  7.07106781e-01  2.14151804e-01]
 [ 5.00000000e-01  5.00000000e-01 -7.07106781e-01  2.14151804e-01]
 [-7.07106781e-01  7.07106781e-01  6.12323400e-17 -1.10856385e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [17]:
T1_1=[[np.cos(theta1+theta2),np.cos(theta1)*-np.sin(theta2),np.sin(theta1),(l2*(np.cos(theta1+theta2)))+(l1*(np.cos(theta1)))],
        [np.sin(theta1)*np.cos(theta2),-np.sin(theta1)*np.sin(theta2),-np.cos(theta1),(l2*(np.cos(theta2)))*(np.sin(theta1))+l1*(np.sin(theta1))],
        [np.sin(theta2),np.cos(theta2),0,(l2*(np.sin(theta2)))+(d1)],
        [0,0,0,1]]

In [18]:
print(np.matrix(T1_1))

[[ 6.12323400e-17 -5.00000000e-01  7.07106781e-01  1.04651804e-01]
 [ 5.00000000e-01 -5.00000000e-01 -7.07106781e-01  2.14151804e-01]
 [ 7.07106781e-01  7.07106781e-01  0.00000000e+00  1.98856385e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [27]:
print(np.cos(90))

-0.4480736161291701
